import * as fs from 'node:fs'
import { createRequire } from 'node:module'
import * as os from 'node:os'
import * as path from 'node:path'

import { afterEach, describe, expect, it } from 'vitest'

const require = createRequire(import.meta.url)
const {
  findAbsoluteSymlinks,
  normalizeRequirementsHeader,
  readPinnedPythonVersion,
  removeLocalInstallMetadata,
  removeOptionalQtArtifacts
}: {
  findAbsoluteSymlinks: (directory: string) => Array<{ path: string; target: string }>
  normalizeRequirementsHeader: (file: string) => void
  readPinnedPythonVersion: () => string
  removeLocalInstallMetadata: (directory: string) => void
  removeOptionalQtArtifacts: (directory: string) => string[]
} = require('../prepare-chemsmart-bridge.js')

const temporaryDirectories: string[] = []

function makeTemporaryDirectory(): string {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'chemsmart-bridge-package-test-'))
  temporaryDirectories.push(directory)
  return directory
}

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    fs.rmSync(directory, { force: true, recursive: true })
  }
})

describe('portable ChemSmart bridge packaging', () => {
  it('uses the repository-pinned Python 3.11 patch release', () => {
    expect(readPinnedPythonVersion()).toMatch(/^3\.11\.\d+$/)
  })

  it('rejects only symlinks that escape through an absolute target', () => {
    const directory = makeTemporaryDirectory()
    fs.writeFileSync(path.join(directory, 'python3.11'), '')
    fs.symlinkSync('python3.11', path.join(directory, 'python'))
    fs.symlinkSync('/usr/bin/python3', path.join(directory, 'external-python'))

    expect(findAbsoluteSymlinks(directory)).toEqual([
      {
        path: path.join(directory, 'external-python'),
        target: '/usr/bin/python3'
      }
    ])
  })

  it('removes local source metadata and bytecode from the packaged runtime', () => {
    const directory = makeTemporaryDirectory()
    const distInfo = path.join(directory, 'chemsmart.dist-info')
    const cache = path.join(directory, '__pycache__')
    fs.mkdirSync(distInfo)
    fs.mkdirSync(cache)
    fs.writeFileSync(path.join(distInfo, 'direct_url.json'), '{"url":"file:///private/source"}')
    fs.writeFileSync(path.join(cache, 'module.pyc'), '')
    fs.writeFileSync(path.join(directory, 'module.py'), '')

    removeLocalInstallMetadata(directory)

    expect(fs.existsSync(path.join(distInfo, 'direct_url.json'))).toBe(false)
    expect(fs.existsSync(cache)).toBe(false)
    expect(fs.existsSync(path.join(directory, 'module.py'))).toBe(true)
  })

  it('removes unused Qt backend artifacts from the portable runtime', () => {
    const directory = makeTemporaryDirectory()
    const sitePackages = path.join(directory, 'lib', 'python3.11', 'site-packages')
    const matplotlibBackends = path.join(sitePackages, 'matplotlib', 'backends')
    const rdkitSping = path.join(sitePackages, 'rdkit', 'sping')
    fs.mkdirSync(path.join(matplotlibBackends, 'qt_editor'), { recursive: true })
    fs.mkdirSync(path.join(rdkitSping, 'Qt'), { recursive: true })
    fs.writeFileSync(path.join(matplotlibBackends, 'qt_compat.py'), '')
    fs.writeFileSync(path.join(matplotlibBackends, 'quantity.py'), '')
    fs.writeFileSync(path.join(rdkitSping, 'Qt', 'pidQt.py'), '')

    expect(removeOptionalQtArtifacts(directory)).toEqual([
      'lib/python3.11/site-packages/matplotlib/backends/qt_compat.py',
      'lib/python3.11/site-packages/matplotlib/backends/qt_editor',
      'lib/python3.11/site-packages/rdkit/sping/Qt'
    ])
    expect(fs.existsSync(path.join(matplotlibBackends, 'qt_compat.py'))).toBe(false)
    expect(fs.existsSync(path.join(rdkitSping, 'Qt'))).toBe(false)
    expect(fs.existsSync(path.join(matplotlibBackends, 'quantity.py'))).toBe(true)
  })

  it('removes checkout paths from the generated requirements header', () => {
    const directory = makeTemporaryDirectory()
    const requirements = path.join(directory, 'requirements.txt')
    fs.writeFileSync(
      requirements,
      [
        '# This file was autogenerated by uv via the following command:',
        '#    uv export --project /Users/researcher/private/chemsmart-studio/services/chemsmart_bridge --frozen',
        'jsonschema==4.25.1'
      ].join('\n')
    )

    normalizeRequirementsHeader(requirements)

    const normalized = fs.readFileSync(requirements, 'utf8')
    expect(normalized).toContain('--project services/chemsmart_bridge')
    expect(normalized).not.toContain('/Users/researcher')
  })
})
