import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')
const AGENT_SKILLS = path.join(ROOT, '.agents', 'skills')
const CLAUDE_SKILLS = path.join(ROOT, '.claude', 'skills')
const PUBLIC_SKILLS = path.join(AGENT_SKILLS, 'public-skills.txt')
const MANAGED_TARGET_PREFIX = '../../.agents/skills/'
const SKILL_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

function readPublicSkills(): string[] {
  const names = fs
    .readFileSync(PUBLIC_SKILLS, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'))

  const seen = new Set<string>()
  for (const name of names) {
    if (!SKILL_NAME.test(name)) throw new Error(`Invalid public skill name: ${name}`)
    if (seen.has(name)) throw new Error(`Duplicate public skill name: ${name}`)
    seen.add(name)
    if (!fs.statSync(path.join(AGENT_SKILLS, name, 'SKILL.md'), { throwIfNoEntry: false })?.isFile()) {
      throw new Error(`Public skill is missing SKILL.md: ${name}`)
    }
  }
  return names.toSorted()
}

function agentIgnore(names: readonly string[]): string {
  return [
    '# AUTO-GENERATED by `pnpm skills:sync`.',
    '# Do not edit manually.',
    '*',
    '!.gitignore',
    '!README*.md',
    '!public-skills.txt',
    ...names.flatMap((name) => [`!${name}/`, `!${name}/**`]),
    ''
  ].join('\n')
}

function claudeIgnore(names: readonly string[]): string {
  return [
    '# AUTO-GENERATED by `pnpm skills:sync`.',
    '# Do not edit manually.',
    '*',
    '!.gitignore',
    '!README*.md',
    ...names.map((name) => `!${name}`),
    ''
  ].join('\n')
}

function expectedTarget(name: string): string {
  return `${MANAGED_TARGET_PREFIX}${name}`
}

function managedClaudeLinks(): Map<string, string> {
  const links = new Map<string, string>()
  for (const entry of fs.readdirSync(CLAUDE_SKILLS, { withFileTypes: true })) {
    const candidate = path.join(CLAUDE_SKILLS, entry.name)
    const stat = fs.lstatSync(candidate)
    if (!stat.isSymbolicLink()) continue
    const target = fs.readlinkSync(candidate)
    if (target.startsWith(MANAGED_TARGET_PREFIX)) links.set(entry.name, target)
  }
  return links
}

function writeIfChanged(file: string, content: string): void {
  if (fs.readFileSync(file, 'utf8') !== content) fs.writeFileSync(file, content)
}

function sync(names: readonly string[]): void {
  fs.mkdirSync(CLAUDE_SKILLS, { recursive: true })
  writeIfChanged(path.join(AGENT_SKILLS, '.gitignore'), agentIgnore(names))
  writeIfChanged(path.join(CLAUDE_SKILLS, '.gitignore'), claudeIgnore(names))

  const allowed = new Set(names)
  for (const [name] of managedClaudeLinks()) {
    if (!allowed.has(name)) fs.unlinkSync(path.join(CLAUDE_SKILLS, name))
  }

  for (const name of names) {
    const link = path.join(CLAUDE_SKILLS, name)
    const target = expectedTarget(name)
    const stat = fs.lstatSync(link, { throwIfNoEntry: false })
    if (stat?.isSymbolicLink() && fs.readlinkSync(link) === target) continue
    if (stat) {
      if (!stat.isSymbolicLink()) throw new Error(`Refusing to replace non-symlink path: ${link}`)
      fs.unlinkSync(link)
    }
    fs.symlinkSync(target, link, 'dir')
  }
}

function check(names: readonly string[]): void {
  const failures: string[] = []
  const expectedAgentIgnore = agentIgnore(names)
  const expectedClaudeIgnore = claudeIgnore(names)
  if (fs.readFileSync(path.join(AGENT_SKILLS, '.gitignore'), 'utf8') !== expectedAgentIgnore) {
    failures.push('.agents/skills/.gitignore is stale; run pnpm skills:sync')
  }
  if (fs.readFileSync(path.join(CLAUDE_SKILLS, '.gitignore'), 'utf8') !== expectedClaudeIgnore) {
    failures.push('.claude/skills/.gitignore is stale; run pnpm skills:sync')
  }

  const allowed = new Set(names)
  for (const [name, target] of managedClaudeLinks()) {
    if (!allowed.has(name)) failures.push(`Stale managed Claude skill link: ${name}`)
    else if (target !== expectedTarget(name)) failures.push(`Incorrect Claude skill target: ${name}`)
  }
  for (const name of names) {
    const link = path.join(CLAUDE_SKILLS, name)
    const stat = fs.lstatSync(link, { throwIfNoEntry: false })
    if (!stat?.isSymbolicLink() || fs.readlinkSync(link) !== expectedTarget(name)) {
      failures.push(`Missing or invalid Claude skill link: ${name}`)
    }
  }
  if (failures.length > 0) throw new Error(failures.join('\n'))
}

function main(): void {
  const command = process.argv[2]
  if (command !== 'sync' && command !== 'check') throw new Error('Usage: manage-skills.ts <sync|check>')
  const names = readPublicSkills()
  if (command === 'sync') sync(names)
  check(names)
  console.log(`Skills ${command} passed for ${names.length} public skills.`)
}

main()
