/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as SettingsDependenciesRouteImport } from './routes/settings/dependencies'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsSplatRouteImport } from './routes/settings/$'
import { Route as AppChemsmartRouteImport } from './routes/app/chemsmart'
import { Route as AppSplatRouteImport } from './routes/app/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDependenciesRoute = SettingsDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSplatRoute = SettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsRoute,
} as any)
const AppChemsmartRoute = AppChemsmartRouteImport.update({
  id: '/chemsmart',
  path: '/chemsmart',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/chemsmart': typeof AppChemsmartRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/app/': typeof AppIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/app/$': typeof AppSplatRoute
  '/app/chemsmart': typeof AppChemsmartRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/app': typeof AppIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/chemsmart': typeof AppChemsmartRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/app/': typeof AppIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/settings'
    | '/app/$'
    | '/app/chemsmart'
    | '/settings/$'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/dependencies'
    | '/settings/provider'
    | '/app/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/$'
    | '/app/chemsmart'
    | '/settings/$'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/dependencies'
    | '/settings/provider'
    | '/app'
    | '/settings'
  id:
    | '__root__'
    | '/app'
    | '/settings'
    | '/app/$'
    | '/app/chemsmart'
    | '/settings/$'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/dependencies'
    | '/settings/provider'
    | '/app/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dependencies': {
      id: '/settings/dependencies'
      path: '/dependencies'
      fullPath: '/settings/dependencies'
      preLoaderRoute: typeof SettingsDependenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$': {
      id: '/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof SettingsSplatRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/chemsmart': {
      id: '/app/chemsmart'
      path: '/chemsmart'
      fullPath: '/app/chemsmart'
      preLoaderRoute: typeof AppChemsmartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppChemsmartRoute: typeof AppChemsmartRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppChemsmartRoute: AppChemsmartRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsRouteChildren {
  SettingsSplatRoute: typeof SettingsSplatRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDependenciesRoute: typeof SettingsDependenciesRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSplatRoute: SettingsSplatRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDependenciesRoute: SettingsDependenciesRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
